theme: jekyll-theme-slate
title: NAEP Results vs Education Spending
description: Addressing common fallacies in comparing the long-term trends in education spending and scores on the National Assessment of Educational Progress (NAEP)
